mol_file_name : "tests/cur.mol"
spin_multiplicity : 1
charge : 0
use_orca : True
orca_exec_command: "/opt/orca5/orca"
num_of_procs : 8
orca_method : "lda sto-3g"
rolling_window_size : 5
rolling_std_threshold : 0.15
rolling_mean_threshold : 1.
num_initial_points : 3
max_steps : 50
