mol_file_name : "tests/mol_1.mol"
exp_name: "mol_1_bocs_1"
spin_multiplicity : 1
charge : -3
use_orca : True
orca_exec_command: "/opt/orca5/orca"
num_of_procs : 8
orca_method : "r2scan-3c"
rolling_window_size : 5
rolling_std_threshold : 0.15
rolling_mean_threshold : 1.
num_initial_points : 3
max_steps : 50
